version: "3"

services:
  webui:
    build:
      context: ./webui
    image: art/webui
    container_name: webui
    restart: always
    ports:
      - "8000:80"
    stdin_open: true
    tty: true

  ia:
    build:
      context: ./image_analysis
    image: art/ia
    container_name: ia
    restart: always
    ports:
      - "2345:2345"
    volumes:
      - "./docker-routes.json:/art/routes.json"
    stdin_open: true
    tty: true

  ir:
    build:
      context: ./ir
    image: art/ir
    container_name: ir
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./docker-routes.json:/art/routes.json"
      - "./ir/ir-requests-db.json:/art/ir/ir-requests-db.json"
      - "./ir/ir-validation-db.json:/art/ir/ir-validation-db.json"
    stdin_open: true
    tty: true

  adaptation:
    build:
      context: ./adaptation
    image: art/adaptation
    container_name: adaptation
    restart: always
    ports:
      - "6397:6397"
    volumes:
      - "./docker-routes.json:/art/routes.json"
      - "./adaptation/sister_cache:/art/adaptation/sister_cache"
    stdin_open: true
    tty: true