language: python
dist: xenial
python:
- 3.6
- 3.7
install:
- pip install pipenv flake8 tox-travis
- pipenv install
script:
- pipenv run flake8
- pipenv run tox
deploy:
  provider: pypi
  user: sobamchan
  on:
    tags: true
  skip_existing: true
  password:
    secure: VeWIHgym835rJmAF6p8lCxF6qiSiIy4FR0iUVde8ft/BTNkH/LFDqyH9Nc5ss2vXCHhqbCKp15KAw66qYdeQZ35l2RQXRdGl7jCnugJXIg1IU/a7Bj+ld3zvfguVUCi9HRenIbGYRnVzN9Kphr3wMO0U70WAi7Nv+m59iCUgI07fMcyL8UowAnB8aB5FFVbJsF72Sro2TI7Ry3Mgjn6pIUbf6EOz33aM7FF511Jwa4c3ogexltoCUVw8drzYLb6ep4iLwDsMQJD+v1g5ZeAv8Iqc4CdbB+cqCxFkFS1Z1GRcp8h9s0GhVctc8jlP9pq1v+zmDUj4DC3CnIwFa4UuKMtScUFROPHYWKMjLmI8g7EBZSWLypwb03RLiVviuXuDo55j4MLlrloI2AclIHAEfAfDw0O/5rZNbDoZEyF36ksoKf0pktN2xtKdollE/2Mw3U6ftGIVBe6lyJ5etO5h6jAIVvsNwkf/PcO+7JaWAXUxRS35WgLhga4HNAHfr8RZ+LtYBby7sMi/beZBIGXWhvumKLWFTTuQVd1eTSQEgAcZ6CrLCyijRRu43100EabyYFFyEnXTi9fgUz8FqHgfvQFFlbZbp8TwF5CWamrtIj3RdWdozsVGNk/ZmPrcwloDU2mJOUHqW4ZYVl5uO5Lhet/IZXUN6p8p7XlA+xnolR8=
